from enum import Enum


class CriterionState(str, Enum):
    SUPPORTED = "SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    REQUIRES_CLINICAL_REVIEW = "REQUIRES_CLINICAL_REVIEW"
